### ISSUE TITLE
py.test example

### ISSUE THREAD

**Issue by sibeliusseraphini** [mahnve/flask-demo#2]
Do you have an example of how to configure codeship with py.test?

**Comment by mahnve** [comment]
Sorry, Codeship is mostly configured in their web gui. I'd suggest using CircleCi which is my favorite of the bunch.

**Comment by mahnve** [comment]
... for that you can look in the circle.yml file

**Comment by sibeliusseraphini** [comment]
could you print your configuration of Codeship please?

**Comment by sibeliusseraphini** [comment]
I will try CircleCi, thanks

**Comment by mahnve** [comment]
My Codeship config is really easy,  the setup part is `pip install -r requirements.txt` and the test part is `nosetest`
